version: "3.8"
services:
  docker-apache:
    image: phpcrypfish:latest
    container_name: docker-apache
    ports:
      - "80:80"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge